**Array Alt Kümesine Erişmek**

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[0:4]

array([20, 21, 22, 23])

In [4]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [5]:
a[1::2]

array([21, 23, 25, 27, 29])

In [6]:
a[0::2]

array([20, 22, 24, 26, 28])

In [7]:
a[2::2]

array([22, 24, 26, 28])

**İki Boyutlu Slice İslemleri**

In [9]:
m = np.random.randint(10, size =(5,5))
m

array([[1, 8, 2, 0, 5],
       [6, 2, 0, 7, 0],
       [3, 6, 8, 1, 0],
       [8, 6, 4, 6, 0],
       [4, 6, 8, 2, 5]])

In [10]:
m[:,0]

array([1, 6, 3, 8, 4])

In [12]:
m[:,4]

array([5, 0, 0, 0, 5])

In [13]:
m[0,:]

array([1, 8, 2, 0, 5])

In [14]:
m[0:2 , 2:4]

array([[2, 0],
       [0, 7]])

In [15]:
m[:, 0:2]

array([[1, 8],
       [6, 2],
       [3, 6],
       [8, 6],
       [4, 6]])

**Alt Küme Üzerinde İşlem Yapmak**

In [17]:
x = np.random.randint(10, size=(5,5))
x

array([[1, 8, 5, 1, 2],
       [1, 8, 6, 7, 8],
       [7, 0, 6, 3, 1],
       [7, 5, 4, 0, 5],
       [3, 0, 5, 6, 8]])

In [18]:
alt_x = x[0:3 , 0:2]
alt_x

array([[1, 8],
       [1, 8],
       [7, 0]])

In [21]:
alt_x[0,0] = 99999
alt_x[2,1] = 400
alt_x

array([[99999,     8],
       [    1,   400],
       [    7,   400]])

In [22]:
x

array([[99999,     8,     5,     1,     2],
       [    1,   400,     6,     7,     8],
       [    7,   400,     6,     3,     1],
       [    7,     5,     4,     0,     5],
       [    3,     0,     5,     6,     8]])

In [23]:
e = np.random.randint(10, size=(5,5))
e

array([[6, 6, 9, 8, 1],
       [0, 1, 0, 5, 4],
       [8, 8, 3, 1, 1],
       [7, 7, 1, 3, 3],
       [5, 5, 1, 1, 2]])

In [24]:
alt_e = e[0:3,0:2].copy()
alt_e

array([[6, 6],
       [0, 1],
       [8, 8]])

In [26]:
alt_e[0,0] = 9999
alt_e

array([[9999,    6],
       [   0,    1],
       [   8,    8]])

In [27]:
e

array([[6, 6, 9, 8, 1],
       [0, 1, 0, 5, 4],
       [8, 8, 3, 1, 1],
       [7, 7, 1, 3, 3],
       [5, 5, 1, 1, 2]])