**Array Sıralama**

In [1]:
import numpy as np

In [5]:
v = np.array([2,9,4,1])

In [6]:
v

array([2, 9, 4, 1])

In [7]:
np.sort(v)

array([1, 2, 4, 9])

In [8]:
v

array([2, 9, 4, 1])

In [9]:
v.sort()

In [10]:
v

array([1, 2, 4, 9])

**İki Boyutlu Sıralama**

In [12]:
m = np.random.normal(20,5,(3,3))

In [13]:
np.sort(m, axis = 1)

array([[ 6.08213496, 13.83396168, 18.39530504],
       [13.96565678, 22.92879408, 23.61818121],
       [ 9.71066626, 16.64667169, 18.46102316]])

In [14]:
np.sort(m, axis = 0)

array([[ 6.08213496,  9.71066626, 16.64667169],
       [18.46102316, 13.83396168, 18.39530504],
       [22.92879408, 13.96565678, 23.61818121]])