**Array Ayırma**

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,99,99,3,2,1])

In [4]:
a,b,c = np.split(x, [3,5])

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([99, 99])

In [9]:
c

array([3, 2, 1])

**İki Boyutlu Ayırma**

In [11]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
ust,alt = np.vsplit(m,[2])

In [15]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
sag,sol = np.hsplit(m, [2])

In [20]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [21]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])