**Array Birleştirme**

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
y = np.array([4,5,6,7])

In [4]:
np.concatenate([x,y])

array([1, 2, 3, 4, 4, 5, 6, 7])

In [5]:
z = np.array([7,8,9])

In [6]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9])

**İki Boyut**

In [7]:
a = np.array([[1,2,3],
             [2,3,4]])

In [8]:
np.concatenate([a,a])

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [9]:
np.concatenate([a,a] , axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4]])