**Numpy ile İki Bilinmeyenli Denklem Çözümü**

In [3]:
import numpy as np

5xO + x1 = 12

x0 + 3x1 = 10

In [5]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [6]:
a

array([[5, 1],
       [1, 3]])

In [7]:
b

array([12, 10])

In [8]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])