***Index ile Erişim***

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10,size=10)
a

array([1, 4, 6, 2, 1, 4, 8, 9, 1, 3])

In [3]:
a[0]

1

In [4]:
a[-1]

3

In [7]:
m = np.random.randint(10, size=(3,5))
m

array([[2, 9, 0, 5, 9],
       [4, 2, 2, 4, 0],
       [2, 4, 8, 3, 5]])

In [8]:
m[0,0]

2

In [10]:
m[2,4]

5

In [11]:
m[1,4] = 2.2

In [12]:
m

array([[2, 9, 0, 5, 9],
       [4, 2, 2, 4, 2],
       [2, 4, 8, 3, 5]])