**Koşullu Eleman İşlemleri**

In [1]:
import numpy as np

In [2]:
v=np.array([1,2,3,4,5])

In [5]:
v < 3

array([ True,  True, False, False, False])

In [7]:
v[v<3]

array([1, 2])

In [8]:
v[v>3]

array([4, 5])

In [9]:
v[v <=4]

array([1, 2, 3, 4])

In [10]:
v[v!=3]

array([1, 2, 4, 5])

In [11]:
v*2

array([ 2,  4,  6,  8, 10])

In [12]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [13]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [14]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)