#Neden Numpy?

In [10]:
a=[1,2,3,4]
b=[2,3,4,5]
    

In [6]:
ab=[]
for i in range(0,len(a)):
    ab.append(a[i]*b[i])

ab    

[2, 6, 12, 20]

In [7]:
import numpy as np

In [11]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])


In [9]:
a*b

array([ 2,  6, 12, 20])

In [12]:
a = np.array([1,2,3,4,5])

In [13]:
type(a)

numpy.ndarray

In [16]:
np.array([3.14 ,30, 4] , dtype="float32")

array([ 3.14, 30.  ,  4.  ], dtype=float32)

Sıfırdan Array Oluşturma

In [18]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [21]:
np.arange(0,31,3)    

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [22]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
np.random.normal(10,4,(3,4))

array([[10.63090164, 10.96329694,  7.52320866, 12.23793494],
       [14.88681798, 10.32168424, 15.1956608 ,  0.36167335],
       [ 6.01003377, 11.71584116, 16.23187826,  6.33314628]])

In [27]:
np.random.randint(0,10,(3,3))

array([[9, 1, 3],
       [1, 4, 1],
       [9, 3, 6]])